// Generated by Wrangler on Sat Jan 04 2025 16:18:55 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface CloudflareEnv {
	PUBLIC_BUCKET_URL: "https://pub-2fde440084bf4d87bd288973a33730e5.r2.dev";
	DATABASE_URL: string;
	NEXT_PUBLIC_API_URL: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}

