name = "college-rejections"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "college-rejections"
database_id = "656b6b22-6e4c-4da8-9eb6-bc340187593b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "college-rejections"

[vars]
PUBLIC_BUCKET_URL = "https://pub-2fde440084bf4d87bd288973a33730e5.r2.dev"